# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7f8aa88f14d6455c1f730fbb8b283c342bd12c55ef1c655a7bf427f4768bf0a86e0a0a90642f5677f7827c026a782d338447b18f801cc448a6bc7465f48c15e2

test:
  secret_key_base: cd64025aebafb6bb6dc06117718eadbf6a44ec36559da9b10fcfe7dd71537abc7eaecb3977fd9fb477de61f883b80b0b9a194b9b66820d84731ba87ad6120b19

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
